# Cobblestone overtop transparency tiles

sheet "tiles"
    padding 1
    output "tiles-cobblestone.png"

extrude 2

trim none

description "tiles-cobblestone.json"
    template "./rawdata/spright/pixijs.inja"

input "./rawdata/tiles/cobblestone-source.png"
    grid 16x16
        sprite "cobblestone-00"
        sprite "cobblestone-01"
        sprite "cobblestone-02"
        sprite "cobblestone-03"
    row 1
        sprite "cobblestone-04"
        sprite "cobblestone-05"
        sprite "cobblestone-06"
        sprite "cobblestone-07"
    row 2
        sprite "cobblestone-08"
        sprite "cobblestone-09"
        sprite "cobblestone-10"
        sprite "cobblestone-11"
    row 3
        sprite "cobblestone-12"
        sprite "cobblestone-13"
        sprite "cobblestone-14"
        sprite "cobblestone-15"
