sheet "sprites"
    padding 1
    output "./public/media/sprites/enemies.png"

description "./public/media/sprites/enemies.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/rogue-like-8x8/Enemies.png"
    trim none
    grid-spacing 1
    grid 8x8
    row 3
        sprite "enemy-scorpion-idle1"
        sprite "enemy-scorpion-idle2"
        sprite "enemy-scorpion-walk1"
        sprite "enemy-scorpion-walk2"
        sprite "enemy-scorpion-attack"
    row 7
        sprite "enemy-snake-walk1"
        sprite "enemy-snake-walk2"
