sheet "sprites"
    padding 1
    output "./public/media/sprites/ground-items.png"

description "./public/media/sprites/ground-items.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/rogue-like-8x8/GroundItems.png"
    trim none
    grid-offset 1, 1
    grid-spacing 1
    grid 8x8
        sprite "ground-item-helmet1"
        sprite "ground-item-helmet2"
        sprite "ground-item-helmet3"
        sprite "ground-item-chest1"
        sprite "ground-item-chest2"
        sprite "ground-item-chest3"
    row 1
        sprite "ground-item-pants1"
        sprite "ground-item-pants2"
        sprite "ground-item-pants3"
        sprite "ground-item-sword1"
        sprite "ground-item-sword2"
        sprite "ground-item-sword3"
    row 2
        sprite "ground-item-shield1"
        sprite "ground-item-shield2"
        sprite "ground-item-shield3"
        sprite "ground-item-blank"
        sprite "ground-item-blank"
        sprite "ground-item-sword4"
    row 3
        sprite "ground-item-helmet4"
        sprite "ground-item-helmet5"
        sprite "ground-item-helmet6"
        sprite "ground-item-chest4"
        sprite "ground-item-chest5"
        sprite "ground-item-chest6"
    row 4
        sprite "ground-item-pants4"
        sprite "ground-item-pants5"
        sprite "ground-item-pants6"
        sprite "ground-item-bow1"
        sprite "ground-item-bow2"
        sprite "ground-item-bow3"
    row 4
        sprite "ground-item-arrow1"
        sprite "ground-item-arrow2"
        sprite "ground-item-arrow3"
