sheet "sprites"
    padding 1
    output "./public/media/sprites/map-objects.png"

description "./public/media/sprites/map-objects.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/rogue-like-8x8/MapObjects.png"
    trim none
    grid-spacing 1
    grid 8x8
    row 0
        sprite "door1"
        sprite "door2"
        sprite "door3"
        sprite "door4"
    row 1
        sprite "blood1"
        sprite "blood2"
        sprite "blood3"
        sprite "blood4"
    row 4
        sprite "dust1"
        sprite "dust2"
        sprite "dust3"
        sprite "dust4"
