sheet "sprites"
    padding 1
    output "./public/media/sprites/player.png"

description "./public/media/sprites/player.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/rogue-like-8x8/Girl-Melee.png"
    trim none
    grid-spacing 1
    grid 8x9
        sprite "girl-melee1-idle"
        sprite "girl-melee1-walk1"
        sprite "girl-melee1-walk2"
    row 1
        sprite "girl-melee1-lunge"
        sprite "girl-melee1-north-walk1"
        sprite "girl-melee1-north-walk2"
    row 1
        sprite "girl-melee1-north-idle"
