sheet "sprites"
    padding 1
    output "./public/media/sprites/trees.png"

description "./public/media/sprites/trees.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/trees.png"
    trim none
    grid 16 32
        sprite "tree1"
            pivot 8, 30
        sprite "tree2"
            pivot 8, 30
