sheet "sprites"
    padding 1
    output "./public/media/sprites/weapons.png"

description "./public/media/sprites/weapons.json"
    template "./rawdata/spright/pixijs.inja"

input "rawdata/rogue-like-8x8/Weapons.png"
    trim none
    grid-offset 1, 1
    grid-spacing 1
    grid 8x8
        sprite "weapon-axe1"
        sprite "weapon-hatchet1"
        sprite "weapon-sword1"
            pivot 3.5, 4.5
    row 1
        sprite "weapon-axe2"
        sprite "weapon-hatchet2"
        sprite "weapon-sword2"
            pivot 3.5, 4.5
    row 2
        sprite "weapon-axe3"
        sprite "weapon-hatchet3"
        sprite "weapon-sword3"
            pivot 3.5, 4.5
    row 3
        sprite "weapon-staff1"
        sprite "weapon-staff2"
        sprite "weapon-staff3"
        sprite "weapon-bow1"
            pivot 4.5, 3.5
    row 4
        sprite "weapon-bow2"
        sprite "weapon-arrow"
            pivot 2.5, 3.5
