<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.2" tiledversion="1.2.4" name="Tileset2" tilewidth="8" tileheight="8" spacing="1" margin="1" tilecount="256" columns="16">
 <image source="../../app/src/assets/media/rogue-like-8x8/Tileset2.png" width="145" height="145"/>
 <tile id="0" type="floor"/>
 <tile id="1" type="floor"/>
 <tile id="2" type="floor"/>
 <tile id="3" type="water"/>
 <tile id="4" type="slime"/>
 <tile id="5" type="wall"/>
 <tile id="6" type="wall"/>
 <tile id="7" type="floor"/>
 <tile id="8" type="floor"/>
 <tile id="9" type="floor"/>
 <tile id="10" type="wall"/>
 <tile id="11" type="wall"/>
 <tile id="12" type="wall"/>
 <tile id="13" type="wall"/>
 <tile id="14" type="wall"/>
 <tile id="15" type="wall"/>
 <tile id="16" type="floor"/>
 <tile id="17" type="floor"/>
 <tile id="18" type="floor"/>
 <tile id="19" type="floor"/>
 <tile id="20" type="floor"/>
 <tile id="21" type="wall"/>
 <tile id="22" type="wall"/>
 <tile id="23" type="floor"/>
 <tile id="24" type="floor"/>
 <tile id="25" type="floor"/>
 <tile id="26" type="wall"/>
 <tile id="27" type="wall"/>
 <tile id="28" type="wall"/>
 <tile id="29" type="wall"/>
 <tile id="30" type="wall"/>
 <tile id="31" type="wall"/>
 <tile id="32" type="door"/>
 <tile id="33" type="wall"/>
 <tile id="34" type="wall"/>
 <tile id="35" type="wall"/>
 <tile id="36" type="wall"/>
 <tile id="37" type="wall"/>
 <tile id="38" type="wall"/>
 <tile id="39" type="wall"/>
 <tile id="40" type="wall"/>
 <tile id="41" type="wall"/>
 <tile id="42" type="wall"/>
 <tile id="43" type="wall"/>
 <tile id="44" type="wall"/>
 <tile id="45" type="wall"/>
 <tile id="46" type="wall"/>
 <tile id="47" type="floor"/>
 <tile id="49" type="wall"/>
 <tile id="50" type="wall"/>
 <tile id="51" type="wall"/>
 <tile id="52" type="wall"/>
 <tile id="53" type="wall"/>
 <tile id="54" type="wall"/>
 <tile id="55" type="wall"/>
 <tile id="56" type="wall"/>
 <tile id="57" type="wall"/>
 <tile id="58" type="wall"/>
 <tile id="59" type="wall"/>
 <tile id="60" type="wall"/>
 <tile id="61" type="wall"/>
 <tile id="62" type="wall"/>
 <tile id="63" type="floor"/>
 <tile id="64" type="floor"/>
 <tile id="65" type="floor"/>
 <tile id="66" type="floor"/>
 <tile id="67" type="floor"/>
 <tile id="68" type="floor"/>
 <tile id="69" type="wall"/>
 <tile id="70" type="wall"/>
 <tile id="71" type="wall"/>
 <tile id="72" type="wall"/>
 <tile id="73" type="wall"/>
 <tile id="74" type="wall"/>
 <tile id="75" type="wall"/>
 <tile id="76" type="wall"/>
 <tile id="77" type="wall"/>
 <tile id="78" type="wall"/>
 <tile id="79" type="floor"/>
 <tile id="93" type="floor"/>
 <tile id="94" type="floor"/>
 <tile id="95" type="floor"/>
 <tile id="109" type="floor"/>
 <tile id="110" type="floor"/>
 <tile id="111" type="floor"/>
</tileset>
